version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  iam-service:
    build: ./iam-service
    container_name: iam-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/iam_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mark0731%

  profiles-service:
    build: ./profiles-service
    container_name: profiles-service
    depends_on:
      - mysql
      - iam-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/profiles_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mark0731%
      APP_ENDPOINTS_IAM_BASE_URL: http://iam-service:8081

  scheduling-service:
    build: ./scheduling-service
    container_name: scheduling-service
    depends_on:
      - mysql
      - profiles-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/scheduling_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mark0731%
      APP_ENDPOINTS_PROFILES_BASE_URL: http://profiles-service:8082

volumes:
  mysql_data:
