spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-headers: "*"
                allowed-methods: "*"
            add-to-simple-url-handler-mapping: true

          routes:
            - id: iam-service
              uri: lb://iam-service
              predicates:
                - Path=/api/v1/authentication/**
                - Path=/api/v1/users/**

            - id: profiles-service
              uri: lb://profiles-service
              predicates:
                - Path=/api/v1/profiles/**

            - id: scheduling-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/reservationsDetails

            - id: catalog-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/catalog

            - id: reviews-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/reviews

            - id: payments-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/payment-sources

server:
  port: 8090

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
