services:
  iam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iam
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/MarceloDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Mark0731%"
      SPRING_PROFILES_ACTIVE: "docker"
      TZ: "America/Lima"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped
    networks:
      - appnet

  profiles:
    build:
      context: ../profiles-service
      dockerfile: Dockerfile
    container_name: profiles-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/MarceloDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Mark0731%"
      APP_ENDPOINTS_IAM_BASE_URL: "http://profiles:8081"
      TZ: "America/Lima"
    ports:
      - "8081:8081"
    depends_on:
      iam:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 25s
    restart: unless-stopped
    networks:
      - appnet

  scheduling:
    build:
      context: ../scheduling-service-pro
      dockerfile: Dockerfile
    container_name: scheduling
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/MarceloDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Mark0731%"
      SPRING_PROFILES_ACTIVE: "docker"
      APP_ENDPOINTS_PROFILES_BASE_URL: "http://profiles:8082"
      TZ: "America/Lima"
    ports:
      - "8082:8082"
    depends_on:
      profiles:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 25s
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
